"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Archive, Bell, Bot, Building2, CalendarClock, Check, CheckCircle2, ChevronDown, Clock3, Cloud, FileSpreadsheet, FileText, Files, FolderKanban, Inbox, LayoutDashboard, ListTodo, Mail, Menu, MessageSquareText, MoreHorizontal, Paperclip, Plus, Search, Send, Settings, ShieldCheck, Sparkles, UserPlus, Users, X } from "lucide-react";
import { checkBackendConnection } from "@/lib/supabase";

type View = "today" | "inbox" | "attention" | "drafts" | "followups" | "tasks" | "approvals" | "team" | "customers" | "files" | "settings";
type SpaceMode = "personal" | "workspace";
type MailItem = { id:number; sender:string; email:string; subject:string; preview:string; time:string; category:string; urgent?:boolean; unread?:boolean; draft:string };

const emails: MailItem[] = [
  { id:1, sender:"Amara Okafor", email:"amara@greenfield.ng", subject:"Need a proposal before Friday", preview:"We reviewed the service options. Could you send a formal proposal with the implementation timeline?", time:"9:42 AM", category:"Sales opportunity", urgent:true, unread:true, draft:"Hi Amara,\n\nThank you for reviewing the service options. I’ll prepare a formal proposal covering the recommended package, implementation timeline and next steps, and send it before Friday.\n\nBest regards,\nKelvin" },
  { id:2, sender:"David Mensah", email:"david@northstar.africa", subject:"Following up on our invoice", preview:"Please confirm whether the revised invoice reached you and when we should expect the next update.", time:"8:18 AM", category:"Payment", unread:true, draft:"Hi David,\n\nThank you for following up. I confirm that the revised invoice was received. I’m reviewing it now and will send you a clear update by the end of today.\n\nBest regards,\nKelvin" },
  { id:3, sender:"Maya from BrightWorks", email:"maya@brightworks.co", subject:"Can we move tomorrow’s meeting?", preview:"A client call has come up at the same time. Would Thursday at 11:00 AM work instead?", time:"Yesterday", category:"Meeting", draft:"Hi Maya,\n\nThursday at 11:00 AM works for me. Please send the updated invitation when convenient.\n\nBest,\nKelvin" },
  { id:4, sender:"Tolu Adebayo", email:"tolu@lanternstudio.com", subject:"Website access details", preview:"I attached the access document and brand notes you requested. Let me know if anything is missing.", time:"Yesterday", category:"Project update", draft:"Hi Tolu,\n\nI’ve received the access document and brand notes. I’ll review everything and let you know if I need anything else.\n\nThank you,\nKelvin" },
];

const personalNav: {id:View; label:string; icon:typeof Inbox; count?:number}[] = [
  {id:"today",label:"Today",icon:LayoutDashboard},{id:"inbox",label:"Inbox",icon:Inbox,count:12},{id:"attention",label:"Needs attention",icon:Sparkles,count:4},{id:"drafts",label:"Draft replies",icon:MessageSquareText,count:3},{id:"followups",label:"Follow-ups",icon:CalendarClock,count:5},{id:"tasks",label:"My tasks",icon:ListTodo,count:4},{id:"customers",label:"Customers",icon:Users},{id:"files",label:"Files",icon:Files},{id:"settings",label:"Settings",icon:Settings}
];
const workspaceNav: {id:View; label:string; icon:typeof Inbox; count?:number}[] = [
  {id:"today",label:"Workspace overview",icon:LayoutDashboard},{id:"tasks",label:"Tasks & projects",icon:FolderKanban,count:9},{id:"approvals",label:"Approvals",icon:ShieldCheck,count:4},{id:"team",label:"Team",icon:Users,count:6},{id:"inbox",label:"Shared inbox",icon:Inbox,count:12},{id:"followups",label:"Follow-ups",icon:CalendarClock,count:5},{id:"customers",label:"Customers",icon:Users},{id:"files",label:"Team files",icon:Files},{id:"settings",label:"Workspace settings",icon:Settings}
];

function Avatar({mail,big=false}:{mail:MailItem;big?:boolean}) { return <span className={`avatar tone-${mail.id} ${big?"big":""}`}>{mail.sender.split(" ").map(v=>v[0]).slice(0,2).join("")}</span>; }

export default function Home(){
  const [view,setView]=useState<View>("today"); const [space,setSpace]=useState<SpaceMode>("workspace"); const [selected,setSelected]=useState(emails[0]); const [approved,setApproved]=useState<number[]>([]); const [query,setQuery]=useState(""); const [menu,setMenu]=useState(false); const [toast,setToast]=useState(""); const [prompt,setPrompt]=useState(""); const [backendReady,setBackendReady]=useState<boolean|null>(null); const upload=useRef<HTMLInputElement>(null);
  const show=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2400)};
  const filtered=useMemo(()=>emails.filter(m=>`${m.sender} ${m.subject} ${m.category}`.toLowerCase().includes(query.toLowerCase())),[query]);
  useEffect(()=>{const doc=document as Document&{modelContext?:{registerTool?:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}};if(!doc.modelContext?.registerTool)return;const c=new AbortController();void Promise.resolve(doc.modelContext.registerTool({name:"show_needs_attention",title:"Show needs attention",description:"Open the priority inbox and list messages that need action.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{setView("attention");return{count:3,subjects:emails.filter(m=>m.unread||m.urgent).map(m=>m.subject)}}},{signal:c.signal})).catch(()=>{});return()=>c.abort()},[]);
  useEffect(()=>{let live=true;void checkBackendConnection().then(ok=>{if(live)setBackendReady(ok)});return()=>{live=false}},[]);
  return <main className="shell">
    <aside className={`sidebar ${menu?"open":""}`}>
      <div className="brand"><span><Sparkles size={20}/></span><b>Agent <i>STEM</i></b><button onClick={()=>setMenu(false)} aria-label="Close"><X/></button></div>
      <div className="space-switcher"><button className={space==="personal"?"chosen":""} onClick={()=>{setSpace("personal");setView("today")}}><span className="mini-avatar">JK</span><span><b>Personal</b><small>Private space</small></span></button><button className={space==="workspace"?"chosen":""} onClick={()=>{setSpace("workspace");setView("today")}}><span className="mini-org"><Building2/></span><span><b>Sirnazam Digital</b><small>Organization workspace</small></span></button></div>
      <button className="ask" onClick={()=>{setView("today");setMenu(false)}}><Bot size={18}/> Ask PLANGO <kbd>⌘K</kbd></button>
      <p className="nav-title">{space==="workspace"?"Organization":"Personal space"}</p><nav>{(space==="workspace"?workspaceNav:personalNav).map(n=>{const Icon=n.icon;return <button key={n.id} className={view===n.id?"active":""} onClick={()=>{setView(n.id);setMenu(false)}}><Icon size={18}/>{n.label}{n.count&&<small>{n.count}</small>}</button>})}</nav>
      <div className="side-bottom"><div className="storage"><span><Cloud size={15}/> {space==="workspace"?"Team cloud":"Personal cloud"}</span><small>2.1 GB / 10 GB</small><i><b/></i></div><button className="profile"><span>JK</span><b>Joseph Kelvin<small>{space==="workspace"?"Owner · Sirnazam Digital":"Personal account"}</small></b><ChevronDown size={15}/></button></div>
    </aside>{menu&&<button className="scrim" onClick={()=>setMenu(false)} aria-label="Close navigation"/>}
    <section className="workspace"><header className="topbar"><button className="icon mobile" onClick={()=>setMenu(true)}><Menu/></button><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search messages, customers and files"/><kbd>⌘ /</kbd></label><div className="actions"><span className="online" title={backendReady===false?"Backend connection unavailable":"PLANGO backend connected"}><i/>{backendReady===null?"Connecting…":backendReady?"Cloud ready":"Offline demo"}</span><button className="icon"><Bell size={19}/><i className="dot"/></button><button className="primary" onClick={()=>show("New action opened")}><Plus size={17}/>New</button></div></header>
      {view==="today"&&(space==="workspace"?<WorkspaceDashboard onView={setView} show={show}/>:<Dashboard onView={setView} onSelect={m=>{setSelected(m);setView("inbox")}} show={show} prompt={prompt} setPrompt={setPrompt}/>)}
      {["inbox","attention","drafts"].includes(view)&&<InboxView mode={view} items={filtered} selected={selected} setSelected={setSelected} approved={approved} approve={()=>{setApproved(v=>[...new Set([...v,selected.id])]);show("Reply approved and queued")}} show={show}/>}
      {view==="followups"&&<FollowUps show={show}/>} {view==="tasks"&&<TasksView workspace={space==="workspace"} show={show}/>} {view==="approvals"&&<ApprovalsView show={show}/>} {view==="team"&&<TeamView show={show}/>} {view==="customers"&&<Customers/>} {view==="files"&&<FileSpace upload={upload} show={show}/>} {view==="settings"&&<SettingsView show={show}/>}
    </section>{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
  </main>
}

function Dashboard({onView,onSelect,show,prompt,setPrompt}:{onView:(v:View)=>void;onSelect:(m:MailItem)=>void;show:(m:string)=>void;prompt:string;setPrompt:(v:string)=>void}){
  return <div className="page"><div className="welcome"><div><p className="eyebrow">WEDNESDAY, SEPTEMBER 16</p><h1>Good morning, Joseph.</h1><p>Here’s what needs your attention first.</p></div><button className="secondary" onClick={()=>show("Briefing reviewed")}><Check size={16}/>Mark briefing reviewed</button></div>
    <div className="brief-grid"><section className="brief"><header><span><Sparkles/></span><div><small>AGENT BRIEFING</small><h2>Four things need your attention</h2></div><em>Updated now</em></header><p>One sales opportunity needs a proposal, an invoice is waiting for confirmation, and two conversations need follow-up today.</p><div>{emails.slice(0,3).map((m,i)=><button key={m.id} onClick={()=>onSelect(m)}><b className={i===0?"hot":""}>{i+1}</b><span><strong>{m.subject}</strong><small>{i===0?"Requested before Friday · High-value opportunity":"Suggested reply is ready for review"}</small></span><em>Review →</em></button>)}</div></section>
      <aside className="day"><header><b><CalendarClock size={18}/>Today</b><MoreHorizontal size={18}/></header><div className="saved"><strong>3</strong><span>replies ready<small>Save about 18 min</small></span></div><hr/><article><time>11:00 AM</time><span><i className="blue"/><b>Project review</b><small>BrightWorks · 45 min</small></span></article><article><time>3:30 PM</time><span><i/><b>Follow-up window</b><small>2 customers · 20 min</small></span></article><button onClick={()=>onView("followups")}>Open schedule →</button></aside></div>
    <SectionHeading title="Priority inbox" copy="Messages PLANGO recommends handling first." action="View all messages" onClick={()=>onView("inbox")}/><section className="priority-list">{emails.slice(0,3).map(m=><button key={m.id} onClick={()=>onSelect(m)}><Avatar mail={m}/><span><b>{m.sender}</b><small>{m.category}</small></span><span><b>{m.subject}</b><small>{m.preview}</small></span><em className={m.urgent?"high":""}>{m.urgent?"High":"Normal"}</em><time>{m.time}</time></button>)}</section>
    <section className="composer"><header><span><Sparkles/></span><div><b>Ask PLANGO</b><small>Work across your inbox, customers and files.</small></div></header><div className="chips"><button onClick={()=>setPrompt("Draft replies to everything urgent")}>Draft urgent replies</button><button onClick={()=>setPrompt("Summarize my unread messages")}>Summarize unread</button><button onClick={()=>setPrompt("Prepare tomorrow's follow-ups")}>Plan tomorrow</button></div><div className="prompt"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask what needs attention, draft a reply, or find a file…"/><Paperclip/><button onClick={()=>{if(prompt.trim()){show("PLANGO request received");setPrompt("")}}}><Send/></button></div><p><CheckCircle2/> PLANGO asks for approval before sending messages or changing files.</p></section>
  </div>
}

function WorkspaceDashboard({onView,show}:{onView:(v:View)=>void;show:(m:string)=>void}){
  const activity=[["Mira Johnson","submitted","September client report","10 min ago"],["David Cole","completed","Update website copy","36 min ago"],["Amina Bello","uploaded","Northstar invoice.pdf","1 hr ago"]];
  return <div className="page workspace-page"><div className="workspace-welcome"><div><p className="eyebrow">SIRNAZAM DIGITAL · ORGANIZATION WORKSPACE</p><h1>Good morning, Joseph.</h1><p>Your team has 4 items waiting for your approval.</p></div><div className="workspace-actions"><button className="secondary" onClick={()=>onView("team")}><UserPlus/>Invite member</button><button className="primary" onClick={()=>show("Task creator opened")}><Plus/>Assign task</button></div></div>
    <section className="org-banner"><div className="org-mark"><Building2/></div><div><small>WORKSPACE PULSE</small><h2>Your organization is moving well</h2><p>Six members are active, 12 tasks are in progress, and four completed items need your decision.</p></div><button onClick={()=>onView("approvals")}>Review 4 approvals <span>→</span></button></section>
    <div className="org-metrics"><button onClick={()=>onView("tasks")}><span className="gold"><ListTodo/></span><b>12</b><small>Tasks in progress</small><em>3 due today</em></button><button onClick={()=>onView("approvals")}><span className="coral"><ShieldCheck/></span><b>4</b><small>Awaiting approval</small><em>Owner decision needed</em></button><button onClick={()=>onView("team")}><span className="blue"><Users/></span><b>6</b><small>Active team members</small><em>2 VAs · 1 Manager</em></button><button onClick={()=>onView("files")}><span className="green"><Files/></span><b>18</b><small>Shared deliverables</small><em>5 uploaded this week</em></button></div>
    <div className="org-columns"><section className="work-panel"><header><div><h2>Team workboard</h2><p>Track delegated work from assignment to approval.</p></div><button onClick={()=>onView("tasks")}>View all →</button></header><div className="task-preview"><article><span className="task-status progress">IN PROGRESS</span><h3>Prepare Q3 client performance report</h3><p>Assigned to Mira Johnson · Virtual Assistant</p><footer><span><i className="avatar tone-3">MJ</i> Due today</span><b>75%</b></footer><div className="progress"><i style={{width:"75%"}}/></div></article><article><span className="task-status review">READY FOR REVIEW</span><h3>Organize Monday management meeting</h3><p>Assigned to David Cole · Executive Assistant</p><footer><span><i className="avatar tone-2">DC</i> Submitted 36 min ago</span><b>100%</b></footer><div className="progress"><i style={{width:"100%"}}/></div></article><article><span className="task-status todo">TO DO</span><h3>Research three payment providers</h3><p>Assigned to Chidi Nwosu · Team Member</p><footer><span><i className="avatar tone-4">CN</i> Due Sep 18</span><b>0%</b></footer><div className="progress"><i style={{width:"0%"}}/></div></article></div></section>
      <aside className="activity-panel"><header><h2>Recent activity</h2><button><MoreHorizontal/></button></header>{activity.map((a,i)=><div key={a[2]}><span className={`avatar tone-${i+1}`}>{a[0].split(" ").map(x=>x[0]).join("")}</span><p><b>{a[0]}</b> {a[1]}<strong>{a[2]}</strong><small>{a[3]}</small></p></div>)}<button className="activity-all">View activity log →</button></aside></div>
    <section className="approval-strip"><span><ShieldCheck/></span><div><b>Nothing is finalized without your approval</b><p>Team members and VAs submit completed tasks, meetings, documents and requests for review. You can approve, reject or request changes.</p></div><button className="primary" onClick={()=>onView("approvals")}>Open approval centre</button></section>
  </div>
}

function TasksView({workspace,show}:{workspace:boolean;show:(m:string)=>void}){
  const tasks=workspace?[["Prepare Q3 client performance report","Mira Johnson","In progress","Today","75%"],["Organize Monday management meeting","David Cole","Ready for review","Today","100%"],["Research three payment providers","Chidi Nwosu","To do","Sep 18","0%"],["Update customer onboarding guide","Amina Bello","In progress","Sep 19","40%"],["Reconcile September invoices","Mira Johnson","To do","Sep 20","0%"]]:[["Review course assignment","You","In progress","Today","60%"],["Finish book chapter","You","To do","Sep 18","0%"],["Prepare weekly plan","You","To do","Sep 19","0%"]];
  return <div className="page standard"><PageTitle overline={workspace?"SIRNAZAM DIGITAL":"PERSONAL SPACE"} title={workspace?"Tasks & projects":"My tasks"} copy={workspace?"Assign work, monitor progress and review every deliverable.":"Plan private work that only you can see."} action={workspace?"Assign task":"New task"} onClick={()=>show("Task creator opened")}/><div className="task-tabs"><button className="active">All tasks</button><button>To do</button><button>In progress</button><button>For review</button><button>Completed</button></div><section className="task-table"><header><span>Task</span><span>Assigned to</span><span>Status</span><span>Due</span><span>Progress</span></header>{tasks.map((t,i)=><button key={t[0]} onClick={()=>show(`${t[0]} opened`)}><span><i className={`priority-dot p${i%3}`}/><b>{t[0]}</b></span><span><i className={`avatar tone-${(i%4)+1}`}>{t[1].split(" ").map(x=>x[0]).join("")}</i>{t[1]}</span><span><em className={`task-status ${t[2]==="Ready for review"?"review":t[2]==="In progress"?"progress":"todo"}`}>{t[2]}</em></span><span>{t[3]}</span><span><b>{t[4]}</b><i className="mini-progress"><i style={{width:t[4]}}/></i></span></button>)}</section></div>
}

function ApprovalsView({show}:{show:(m:string)=>void}){
  const approvals=[["September client performance report","Mira Johnson","Document","Submitted 10 min ago"],["Monday management meeting agenda","David Cole","Meeting","Submitted 36 min ago"],["Northstar revised invoice","Amina Bello","Payment","Submitted 1 hr ago"],["Lagos client visit itinerary","Mira Johnson","Travel","Submitted yesterday"]];
  return <div className="page standard"><PageTitle overline="OWNER CONTROL" title="Approval centre" copy="Review work before anything is sent, booked, published or finalized."/><div className="approval-summary"><b>4 awaiting your decision</b><p>You remain in control. PLANGO never finalizes team work automatically.</p></div><section className="approval-list">{approvals.map((a,i)=><article key={a[0]}><div className={`approval-icon a${i}`}><ShieldCheck/></div><div><span><em>{a[2]}</em><small>{a[3]}</small></span><h3>{a[0]}</h3><p>Prepared by <b>{a[1]}</b> and submitted for your review.</p></div><footer><button className="secondary" onClick={()=>show("Changes requested")}>Request changes</button><button className="reject" onClick={()=>show("Item rejected")}>Reject</button><button className="primary" onClick={()=>show("Item approved")}>Approve</button></footer></article>)}</section></div>
}

function TeamView({show}:{show:(m:string)=>void}){
  const team=[["Joseph Kelvin","Owner","Full access","Active"],["Mira Johnson","Virtual Assistant","Tasks, files, requests","Active"],["David Cole","Executive Assistant","Calendar, meetings, files","Active"],["Amina Bello","Manager","Team and project management","Active"],["Chidi Nwosu","Member","Assigned tasks only","Active"],["Sarah Cole","Viewer","Read-only access","Invited"]];
  return <div className="page standard"><PageTitle overline="SIRNAZAM DIGITAL" title="Team & access" copy="Invite people, assign roles and control exactly what each person can do." action="Invite member" onClick={()=>show("Invitation form opened")}/><section className="role-cards"><div><span><ShieldCheck/></span><b>Owner approval</b><p>Final control over every action and workflow transition.</p></div><div><span><UserPlus/></span><b>Flexible roles</b><p>Owner, Admin, Manager, Assistant, Member and Viewer.</p></div><div><span><FolderKanban/></span><b>Visible work</b><p>Track assignments, deliverables and activity in real time.</p></div></section><section className="team-table"><header><span>Member</span><span>Role</span><span>Access</span><span>Status</span><span/></header>{team.map((m,i)=><div key={m[0]}><span><i className={`avatar tone-${(i%4)+1}`}>{m[0].split(" ").map(x=>x[0]).join("")}</i><b>{m[0]}</b></span><span><em>{m[1]}</em></span><span>{m[2]}</span><span><i className={m[3]==="Active"?"online-dot":"invited-dot"}/>{m[3]}</span><button><MoreHorizontal/></button></div>)}</section></div>
}

function InboxView({mode,items,selected,setSelected,approved,approve,show}:{mode:View;items:MailItem[];selected:MailItem;setSelected:(m:MailItem)=>void;approved:number[];approve:()=>void;show:(m:string)=>void}){
  const title=mode==="attention"?"Needs attention":mode==="drafts"?"Draft replies":"Inbox"; const list=mode==="attention"?items.filter(m=>m.unread||m.urgent):mode==="drafts"?items.filter(m=>!approved.includes(m.id)):items;
  return <div className="mail-layout"><section className="mail-list"><header><div><p className="eyebrow">SMART INBOX</p><h1>{title}</h1></div><MoreHorizontal/></header><div className="filters"><b>All</b><span>Unread</span><span>Priority</span><small>{list.length} messages</small></div>{list.map(m=><button key={m.id} className={selected.id===m.id?"selected":""} onClick={()=>setSelected(m)}><Avatar mail={m}/><span><span><b>{m.sender}</b><time>{m.time}</time></span><strong>{m.subject}</strong><small>{m.preview}</small><em>{m.category}</em></span></button>)}</section>
    <article className="mail-detail"><nav><button><Archive/></button><button onClick={()=>show("Follow-up reminder created")}><Clock3/></button><button><MoreHorizontal/></button></nav><div className="message"><label><Sparkles/>{selected.category}</label><h2>{selected.subject}</h2><div className="sender"><Avatar mail={selected}/><span><b>{selected.sender}</b><small>{selected.email}</small></span><time>{selected.time}</time></div><div className="body"><p>Hi Kelvin,</p><p>{selected.preview}</p><p>Thank you,<br/>{selected.sender.split(" ")[0]}</p></div><aside className="insight"><b><Sparkles/>Agent insight</b><p><strong>Intent:</strong> A response is recommended today.</p><p><strong>Suggested action:</strong> Review the prepared reply and approve when ready.</p></aside><section className="draft"><header><b><Bot/>Suggested reply</b><span>Professional · concise</span></header><textarea defaultValue={selected.draft}/><footer><button className="secondary" onClick={()=>show("Draft copied")}>Copy</button><button className="primary" onClick={approve}>{approved.includes(selected.id)?<><Check/>Approved</>:<><Send/>Approve & queue</>}</button></footer></section></div></article></div>
}

function FollowUps({show}:{show:(m:string)=>void}){const rows=[["Amina Bello","Website redesign enquiry","4 days quiet","Today","High"],["Chidi Nwosu","Training package","3 days quiet","Today","Medium"],["Sarah Cole","Automation consultation","Waiting for documents","Tomorrow","Medium"],["Kofi Owusu","Annual support renewal","Renewal in 7 days","Sep 18","Normal"]];return <div className="page standard"><PageTitle overline="RELATIONSHIPS" title="Follow-ups" copy="Keep every promising conversation moving." action="Create follow-up" onClick={()=>show("Follow-up creator opened")}/><Metrics items={[["5","Due this week"],["2","Overdue"],["68%","Reply rate"]]}/><section className="table"><header><span>Customer</span><span>Conversation</span><span>Status</span><span>Due</span><span>Priority</span></header>{rows.map((r,i)=><div key={r[0]}><span><span className={`avatar tone-${i+1}`}>{r[0].split(" ").map(x=>x[0]).join("")}</span><b>{r[0]}</b></span><span>{r[1]}</span><span>{r[2]}</span><span>{r[3]}</span><span><em>{r[4]}</em><button onClick={()=>show(`Follow-up prepared for ${r[0]}`)}><Sparkles/></button></span></div>)}</section></div>}
function Customers(){const rows=[["Amara Okafor","Greenfield Ltd","Proposal requested","₦850,000"],["David Mensah","Northstar Africa","Invoice review","₦320,000"],["Maya Adjei","BrightWorks","Active project","₦1,200,000"],["Tolu Adebayo","Lantern Studio","Onboarding","₦480,000"]];return <div className="page standard"><PageTitle overline="CUSTOMER MEMORY" title="Customers" copy="Every conversation, commitment and next step in one place." action="Add customer"/><Metrics items={[["24","Active customers"],["7","Open opportunities"],["₦2.85m","Pipeline value"]]}/><section className="customer-grid">{rows.map((r,i)=><button key={r[0]}><span className={`avatar big tone-${i+1}`}>{r[0].split(" ").map(x=>x[0]).join("")}</span><span><b>{r[0]}</b><small>{r[1]}</small></span><em>{r[2]}</em><footer><span><small>VALUE</small><b>{r[3]}</b></span><span><small>LAST CONTACT</small><b>{i<2?"Today":"Yesterday"}</b></span></footer></button>)}</section></div>}
function FileSpace({upload,show}:{upload:React.RefObject<HTMLInputElement|null>;show:(m:string)=>void}){const list=[["Greenfield proposal.pdf","PDF","2.4 MB"],["September leads.xlsx","Spreadsheet","680 KB"],["Client requirements.docx","Document","1.1 MB"]];return <div className="page standard"><input ref={upload} hidden type="file" onChange={e=>e.target.files?.[0]&&show(`${e.target.files[0].name} is ready to upload`)}/><PageTitle overline="CLOUD WORKSPACE" title="Files" copy="Read, organize and work with every document using your agent." action="Upload file" onClick={()=>upload.current?.click()}/><section className="file-actions"><button><FileText/><span><b>Work with a PDF</b><small>Read, summarize, split or merge</small></span><Plus/></button><button><FileText/><span><b>Create a document</b><small>Letters, proposals and reports</small></span><Plus/></button><button><FileSpreadsheet/><span><b>Analyse a spreadsheet</b><small>Formulas, tables and charts</small></span><Plus/></button></section><SectionHeading title="Recent files" copy="Your most recently opened work."/><section className="files">{list.map((f,i)=><button key={f[0]}><span>{i===1?<FileSpreadsheet/>:<FileText/>}</span><span><b>{f[0]}</b><small>{f[1]}</small></span><em>{f[2]}</em><time>{i===0?"Today":"Yesterday"}</time><MoreHorizontal/></button>)}</section></div>}
function SettingsView({show}:{show:(m:string)=>void}){return <div className="page standard narrow"><PageTitle overline="CONTROL CENTRE" title="Settings" copy="Choose how your agent works and what it can do."/><section className="settings"><Setting icon={<Mail/>} title="Email connection" copy="Connect Gmail to replace the demonstration inbox with your messages." action={<button className="primary" onClick={()=>show("Secure Gmail connection is the next integration")}>Connect Gmail</button>}/><Setting icon={<CheckCircle2/>} title="Approval before sending" copy="PLANGO must ask before sending messages." action={<Toggle/>}/><Setting icon={<Bell/>} title="Daily attention briefing" copy="Receive one focused summary of messages and follow-ups." action={<Toggle/>}/></section></div>}

function PageTitle({overline,title,copy,action,onClick}:{overline:string;title:string;copy:string;action?:string;onClick?:()=>void}){return <div className="page-title"><div><p className="eyebrow">{overline}</p><h1>{title}</h1><p>{copy}</p></div>{action&&<button className="primary" onClick={onClick}><Plus/>{action}</button>}</div>}
function SectionHeading({title,copy,action,onClick}:{title:string;copy:string;action?:string;onClick?:()=>void}){return <div className="section-heading"><div><h2>{title}</h2><p>{copy}</p></div>{action&&<button onClick={onClick}>{action} →</button>}</div>}
function Metrics({items}:{items:string[][]}){return <div className="metrics">{items.map((m,i)=><div key={m[1]} className={`m${i}`}><b>{m[0]}</b><span>{m[1]}</span></div>)}</div>}
function Setting({icon,title,copy,action}:{icon:React.ReactNode;title:string;copy:string;action:React.ReactNode}){return <div><span>{icon}</span><p><b>{title}</b><small>{copy}</small></p>{action}</div>}
function Toggle(){return <label className="toggle"><input type="checkbox" defaultChecked/><i/></label>}
